### ISSUE TITLE
ResolvedContext.get_environ() is missing key / values from parent_environ

### ISSUE THREAD

**Issue by ColinKennedy** [AcademySoftwareFoundation/rez#1316] opened 2022-06-07 03:29 UTC
[ResolvedContext.get_environ()](https://github.com/AcademySoftwareFoundation/rez/blob/f8c6b5b0cfbab17c9102a130bf56080e99f014b8/src/rez/resolved_context.py#L1107-L1118) doesn't return parent information, even if a variable is explicitly set via `context.get_environ(self, parent_environ={"FOO": "bar"})`. This behavior differs from `execute_command(..., parent_environ={"FOO": "bar"})` and `execute_shell(parent_environ={"FOO": "bar"})`, which both include `FOO` in the resulting resolve.

**Environment**
* OS: CentOS 7
* Rez version: 2.109.0
* Rez python version: 3.7

**To Reproduce**
Make a Python file like this:

```python
from rez import resolved_context

requests = []
context = resolved_context.ResolvedContext(requests)
environment = context.get_environ(parent_environ={"FOO": "bar})
```

**Expected behavior**
For FOO to be included in the `environment` variable, just like how doing `export FOO=bar && rez-env -- echo '$FOO'` prints `bar`.

**Actual behavior**
environment does not include FOO unless one of the package requests in `requests` modifies it.

At the moment I'm getting around the problem by doing this

```python
environment = {"FOO": "bar"}
environment.update(context.get_environ(parent_environ=environment))
```

Rez should be managing the environment variables, so I find this hack to be a bit fragile. I'm not sure if it is "guaranteed" to work and would rather Rez handle it for me.

**Comment by instinct-vfx** [comment] 2022-06-07 07:11
I am not sure i understand the environment and what exactly does not work. How are DISPLAY and FOO set in the parent env?

**Comment by ColinKennedy** [comment] 2022-06-07 07:20
Ah sorry, bad copy-paste. The real situation this occurred was when I was trying to figure out why the DISPLAY variable wasn't getting passed through. I renamed it to FOO for this ticket, to make it more generic.

I've updated the issue to remove all references to DISPLAY.

**Comment by instinct-vfx** [comment] 2022-06-07 07:33
I am not sure how this is handled on Linux platforms. On Windows rez takes environment variables from the registry and only loads system level environment variables, not the ones defined in the scope of the current shell. The reason is to prevent environment variables from a rez created shell into a nested rez created shell. An example would be resolving a python 2.7 shell and then a python 3 shell inside. That would mix up the PYTHONPATHS.
If i see this correctly in the code then on Linux it runs with --norc to yield a similar result. Hence your profile is never executed for the child shell (at least not in the context of environment variable inheritance).
I think the reason why `export FOO=bar && rez-env -- echo '$FOO'` seems to work is that `$FOO` is expanded in the parent shell already so the command that is getting executed in the child shell is `echo bar` rather than `echo $FOO`. I think it will also break if you escape the dollar so that it gets passed into the child shell.

**Comment by ColinKennedy** [comment] 2022-06-07 07:46
> On Windows rez takes environment variables from the registry and only loads system level environment variables, not the ones defined in the scope of the current shell.

I wasn't aware of this, that's interesting info. I didn't realize there was that difference

> An example would be resolving a python 2.7 shell and then a python 3 shell inside. That would mix up the PYTHONPATHS.

Just want to clarify - In Linux and in my experience, the scenario you mentioned would not mix PYTHONPATHs because the second rez-env's packages would first override PYTHONPATH on first reference and then append to PYTHONPATH for each subsequent call. The scenarios where a mixture could occur are:

- [all_parent_variables](https://github.com/AcademySoftwareFoundation/rez/wiki/Configuring-Rez#all_parent_variables) is True
- PYTHONPATH is included in [https://github.com/AcademySoftwareFoundation/rez/wiki/Configuring-Rez#parent_variables](parent_variables)
- `env.PYTHONPATH.append(os.environ["PYTHONPATH"])` is defined in a package `commands()` / `pre_commands()` or something.

I believe Windows would work the same way. The only exception to the rule are variables which a package in the first resolve defines and then the second resolve does not. e.g. if the first `rez-env` defines FOO somewhere but the second `rez-env` doesn't define `FOO`, `FOO` is still in the nested `rez-env`

**Comment by nerdvegas** [comment] 2022-06-07 09:43
This is by design - get_environ() is returning only those env-vars set by rez. The env-vars that you provide in `parent_environ` potentially influence the env-vars that rez sets, but that's all, they don't need to be in the result. The result intentionally tells you what env-vars were set by the context - if it included more than that, then you wouldn't know which is which.

For example, consider this package_commands, where USER impacts the resulting environ:

```
def commands():
    if env.USER == "jbloggs":
        env.PATH.append("{root}/joes_tools")
```

Here USER affects the resolve, but the resolve doesn't set USER, so it's not returned by get_environ().

If the env-vars that potentially impact the environ are important to you, then manually combining them as per your second example is the correct approach. In a normal rez-env (and following our example here), nothing is amiss - USER affected the resolved environ, and USER is still set within that environ (because rez doesn't alter env-vars unless its packages do, besides various REZ_* vars of course).


"""However in Linux there's a 4th scenario where variables which a package in the first resolve defines and then the second resolve does not will carry through. e.g. if the first rez-env defines FOO somewhere but the second rez-env doesn't define FOO, FOO is still in the nested rez-env"""

Just wanted to mention about this also, as it comes up now and then. This, again, is by design. Rez does not treat the parent environ as a special case just because it also is a rez-resolved env. The behaviour is the same - the second resolve will leave FOO unchanged - regardless of whether a parent rez session set it, or a user set it - unless a package in the resolve changes it specifically.

Hth, closing.

**Closed by nerdvegas** 2022-06-07 09:43 UTC
Labels: bug

**Comment by nerdvegas** [comment] 2022-06-07 09:59
To add one more kinda related point. Having said what I did above, it's also true that we would benefit from having greater control over how env-vars are managed, down to the per-var level ideally. For example, a problem we have at the moment is that PATH doesn't really behave ideally during execution of the context - the system paths are only appended at the end (if you attempted to do an `ls` in a package's commands for eg, it would probably fail). It would be good to be able to say, "append to PATH, but keep the pre-rez value of PATH always appended at the end." In other words, if 3 packages appended A, B and C to PATH, and if PATH (before any rez-env) was X:Y, then, during the resolve, PATH would be set first to A:X:Y, then A:B:X:Y, and finally A:B:C:X:Y.

Were we to have this level of control, perhaps we could think about giving more control over what to do with extra vars set by rez packages that might 'pollute' a child rez shell (and LD_PRELOAD comes to mind). Honestly though I'm still on the fence about it - who's to say that LD_PRELOAD, whilst set by the parent rez shell, wasn't also set explicitly and intentionally by the user afterward, who is now going to be thoroughly confused when it disappears from their next rez-env?






See the existing ticket on this topic: https://github.com/AcademySoftwareFoundation/rez/issues/737

**Comment by nerdvegas** [comment] 2022-06-07 23:27
To be absolutely clear:

- get_environ() returns only the vars that rez packages in the resolve have
altered. This is because rez doesn't 'care' about any others - they remain
unchanged
- parent_environ is there so you can supply an environ dict different to
current os.environ. If None, os.environ is used (as per docstring).

So, to get the _exact_ environ that you'd have in the rez-env, where you
also want to set FOO, you would actually do this:

```
environment = os.environ.copy()
environment.update({"FOO": "bar"})
environment.update(context.get_environ(parent_environ=environment))
```

This will give you the environ equivalent to if you had done
```
]$ export FOO=bar && rez-env ...
```

One more subtlety - get_environ works by running the context through the
"python" interpreter (a special non-shell case). That means that if any
packages used the `source` function, and that caused an env-var to be set,
that would not be picked up here (because there's no shell to source the
script!).

I think it would be worth updating the docstring to make this more clear.
Ticket: https://github.com/AcademySoftwareFoundation/rez/issues/1317

Ps - Tbh I'm not really aware of get_environ being used much, we never used
it at Method to my knowledge. If you wanted a 100% reliable version of this
function (ie exactly what a shell would give), that would be something
different - you'd have to optionally specify the shell to use, and a
standard function would have to be added to every shell impl to be able to
extract the resulting environ dict from it. In this version, we would have
no choice other than to return the full environ, because it's impossible to
know what a source command might have set.

**Comment by ColinKennedy** [comment] 2022-06-07 23:42
>  If you wanted a 100% reliable version of this function (ie exactly what a shell would give), that would be something different

Maybe in the future but FWIW my case for `get_environ()` is for a debug tool, nothing fancy. Accuracy is ideal but if we can get 99% of the way there and only `source()` or some other less common features aren't supported, that'd be okay, I think. I'll just add a disclaimer that the view may not show 100% everything. Thank you for the in-depth explanation!
