### ISSUE TITLE
dyld Library not loaded python error

### ISSUE THREAD

**Issue by Sharkitty** [AcademySoftwareFoundation/rez#1818] opened 2024-09-02 16:33 UTC
I've been having this error from `dyld` when using `rez` on a mac. It completely prevents me from using `rez` on this machine. Any `rez` command triggers the error, and `rez` was working fine on this machine until I came back from vacations, updated homebrew packages and tried to use `rez`. I verified that the python `rez` is trying to use exists, and that the version matches.

```
dyld[39849]: Library not loaded: /opt/homebrew/Cellar/python@3.9/3.9.19/Frameworks/Python.framework/Versions/3.9/Python
  Referenced from: <C6C5562D-62A4-3A38-A1BA-EF1567945629> /Users/normaal/rez/bin/python
  Reason: tried: '/opt/homebrew/Cellar/python@3.9/3.9.19/Frameworks/Python.framework/Versions/3.9/Python' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/python@3.9/3.9.19/Frameworks/Python.framework/Versions/3.9/Python' (no such file), '/opt/homebrew/Cellar/python@3.9/3.9.19/Frameworks/Python.framework/Versions/3.9/Python' (no such file), '/Library/Frameworks/Python.framework/Versions/3.9/Python' (no such file), '/System/Library/Frameworks/Python.framework/Versions/3.9/Python' (no such file, not in dyld cache)
[1]    39849 abort      rez
```

**Environment**
* OS: Mac Ventura 13.2
* Rez version: 2.114.1
* Rez python version: 3.9.19

**To Reproduce**
Run `rez` on a Mac Ventura 13.2.

**Expected behavior**
`rez` should work normally.

**Actual behavior**
Produces the aforementioned error.

**Comment by jrrbarros** [comment] 2024-09-11 16:43
I had this issue but using poetry.

I had to do the following:

### Use pyenv for Managing Python Versions (Optional):

If you often work with different Python versions, you may find pyenv useful to manage them easily:

`brew install pyenv`
After installation, install Python 3.9 and set it as the default version:

```
pyenv install 3.9.19
pyenv global 3.9.19
```

4. Recreate the Virtual Environment:
Once your Python setup is fixed, recreate the virtual environment in your project and reinstall the dependencies:

```
rm -rf .venv
poetry env use python3.9
poetry install --no-root
```

See if it works.

**Comment by Sharkitty** [comment] 2024-09-12 09:24
> I had this issue but using poetry.
> 
> I had to do the following:
> ### Use pyenv for Managing Python Versions:
> 
> If you often work with different Python versions, you may find pyenv useful to manage them easily:
> 
> `brew install pyenv` After installation, install Python 3.9 and set it as the default version:
> 
> ```
> pyenv install 3.9.19
> pyenv global 3.9.19
> ```
> 
>     4. Recreate the Virtual Environment:
>        Once your Python setup is fixed, recreate the virtual environment in your project and reinstall the dependencies:
> 
> 
> ```
> rm -rf .venv
> poetry env use python3.9
> poetry install --no-root
> ```
> 
> See if it works.

I don't see any venv in rez files :confused: Btw this machine has been upgrade to Sonoma 14.6.1 since I opened the issue and the bug persists.

**Comment by vanridal** [comment] 2024-10-10 10:20
At a guess this looks to be an issue with the python installed on the Mac, rez is contain inside a venv which needs the underlying python interpreter and system packages that installed it, the rez venv can no longer find the python interpreter probably due to homebrew updating it and the path to the interpreter has changed, my advice is to re-install rez so that the virtual environment is re-created.

**Comment by JeanChristopheMorinPerso** [comment] 2024-10-13 19:31
This can happen for various reasons and it's not related to rez. You say that you use pyenv to manage python, but the error you gave us says that `/opt/homebrew/Cellar/python@3.9/3.9.19/Frameworks/Python.framework/Versions/3.9/Python` was used. This leads me to think that your environment might not be like you thought it should be.

Issues like these should not happen if the `install.py` script is used with the right python. (but pyenv pythons can break when upgrading your system, because AFAIK it will compile python using your system's libraries).

I'll close this issue for now since I don't think it the issue is with rez.

Like @vanridal suggested, maybe try to re-install rez.

**Closed by JeanChristopheMorinPerso** 2024-10-13 19:31 UTC
Labels: bug
