### ISSUE TITLE
doskey history does not function inside a rez environment

### ISSUE THREAD

**Issue by Anti-Distinctlyminty** [AcademySoftwareFoundation/rez#1460] opened 2023-03-15 09:37 UTC
doskey history does not function inside a rez environment

**Environment**
* OS windows-10.0.19045.SP0
* Rez 2.112.0
* Rez python version 3.9.13

**To Reproduce**
1. start an environment with `rez-env`
2. Type `echo whatever`
3. Hit the up arrow to recall the last command

**Expected behavior**
The last command should be recalled

**Actual behavior**
Nothing happens

I've tried running `doskey /reinstall` and `doskey /history`. I'm not sure what's going on, but it seems that doskey history is non-functiona
Macros seem to work fine however.

**Comment by JeanChristopheMorinPerso** [comment] 2023-03-15 20:55
Duplicate of #1234 and #1240

**Comment by JeanChristopheMorinPerso** [comment] 2023-03-15 20:56
Duplicate of #1234

**Comment by JeanChristopheMorinPerso** [comment] 2023-03-15 21:01
Hi @Anti-Distinctlyminty Thanks for reporting this. As you can see in my previous comment, it was already reported previously, so I'll close your issue. You can continue the conversation in #1234 .

**Closed by JeanChristopheMorinPerso** 2023-03-15 21:01 UTC
Labels: bug, topic:windows, shell
